### ISSUE TITLE
Implement me. Unknown stdin file type

### ISSUE THREAD

**Issue by coderdiaz** [TooTallNate/keypress#20]
I have a problem with the example for instance the keyboard event, my application say 'Implement me. Unknown stdin file type' and break my electron application.

How I can solve this? Is a issue?

Thanks, guys, this is my code.

``` js
var keypress = require('keypress');

keypress(process.stdin);

process.stdin.on('keypress', function(ch, key) {
    console.log('got "Keypress', key);
});
process.stdin.setRawMode(true);
process.stdin.resume();
```

**Comment by murrah** [comment]
Same here. Used the sample code from the Readme file. Same if I do this: 

const readline = require('readline');
readline.emitKeypressEvents(process.stdin);

Running under NW.js v 22
